# Generated by Django 3.2 on 2022-03-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consec', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaSalida', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura', models.IntegerField(default=0)),
                ('numcita', models.IntegerField(default=0)),
                ('salidaClinica', models.CharField(default='N', max_length=1)),
                ('salidaDefinitiva', models.CharField(default='N', max_length=1)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
