# Generated by Django 3.2 on 2022-03-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('clinico', '0001_initial'),
        ('contratacion', '0002_procedimientos_usuarioregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='id_centro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.centros'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_ciudad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.ciudades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_departamento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.departamentos'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_especialidad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='id_tipo_doc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='diagnosticos',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaInterconsulta', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='estadosInterconsulta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.estadosinterconsulta'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='plantaConsultado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='diagnosticos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoIncapacidades', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='tiposIncapacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposincapacidad'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaResul', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='estadoExamenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.estadoexamenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.examenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='diagnosticos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dxPpal', to='clinico.diagnosticos'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='historialDiagnosticosCabezote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='clinico.historialdiagnosticoscabezote'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='tiposDiagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tiposDiagnostico', to='clinico.tiposdiagnostico'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='antecedentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.antecedentes'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoAntecedentes', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='tiposAntecedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposantecedente'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.historia'),
        ),
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='estadoExamenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.estadoexamenes'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='historiaExamenesCabezote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.historiaexamenescabezote'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contratacion.procedimientos'),
        ),
        migrations.AddField(
            model_name='historia',
            name='causasExterna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.causasexterna'),
        ),
        migrations.AddField(
            model_name='historia',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.dependencias'),
        ),
        migrations.AddField(
            model_name='historia',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria', to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='especialidades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='historia',
            name='planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tiposdocumento'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tiposFolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposfolio'),
        ),
        migrations.AddField(
            model_name='historia',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='TiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposexamen'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidadesMedicos1', to='clinico.especialidades'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planta.planta'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta', to='planta.planta'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='tiposAntecedente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.tiposantecedente'),
        ),
    ]
